services:
  mysql:
    image: 'mysql:8.0'
    container_name: salem-mysql
    environment:
      - 'MYSQL_DATABASE=qlbh'
      - 'MYSQL_ROOT_PASSWORD=1111'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - salem-network

  app:
    build: .
    container_name: salem-app
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/qlbh
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1111
    networks:
      - salem-network

volumes:
  mysql_data:

networks:
  salem-network:
    driver: bridge
